### PR TITLE
Feature/framework+cocoa async fix

### PR DESCRIPTION
**Pull request by roballie**
Create a CocoaHTTPServer framework.
Fix crash when using self signed cert + newest version of CocoaAsyncSocket

### CODE REVIEW

**Comment by LGriffioen** [comment]
why does this need the httpServer project if the parent project is supposed to have it?

**Comment by LGriffioen** [comment]
we will want to merge https://github.com/TechSmith/CocoaHTTPServer/pull/9. looks like mostly warning fixes and only a very minor merge conflict

**Comment by roballie** [comment]
You drag the project into the parent workspace, just like any other framework.

**Comment by LGriffioen** [comment]
oh, so the parent project doesn't need to have it's own http server submodule then?

**Comment by roballie** [comment]
it does.  the parent project has the submodule for TSCConnect, CocoaAsyncSocket and CocoaHTTPServer.  Then you drag the project for each of those into the parent workspace.  Embed or link TSCConnect framework to the parent project and it should be good.

**Comment by roballie** [comment]
can look at https://github.com/TechSmith/TSCConnect-TestHarness to see how to submodule/link

**Comment by LGriffioen** [comment]
ok, that's what i did and it works, but that's why im confused that you're checking in the project file for http server when the parent app already has it

**Comment by roballie** [comment]
how does the parent app have a project for a submodule?

**Comment by LGriffioen** [comment]
when you check out a submodule, it gets the project file and all the source code

**Comment by roballie** [comment]
but CocoaHTTPServer didn't have a project file.  It comes with a bunch of samples.  Were you using one of the sample projects?

**Comment by LGriffioen** [comment]
Screen Shot 2020-05-19 at 9 06 57 AM

**Comment by roballie** [comment]
that's the one I made and is in question.

**Comment by LGriffioen** [comment]
oh, gotcha

**Comment by roballie** [comment]
it's kind of confusing.  Before this project existed, TSCConnect just literally compiled the source code like it was part of the TSCConnect project.  Felt dirty.  It also led to a hard to fix bug.

**Review by LGriffioen — APPROVED** [review]

**Pull request merged**
